name: 435f534c-e49b-43c3-9bd6-3393100bef3f
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9
  - pandas
  - intake
  - intake-xarray
  - hvplot
  - xarray
  - aiohttp
  - scikit-image
  - pooch